- name: Construye el template y envia la configuracion de VLANs a los switches
  hosts: cisco_switches
  gather_facts: false
  connection: network_cli
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Construyendo templates
      template:
        src=templates/vlans.j2
        dest=candidate_config/{{ inventory_hostname }}

  
    - name: Enviando configuraciones      
      napalm_install_config:
        hostname={{ hostname }}
        username={{ username }}
        password={{ password }}
        dev_os={{ os }}
        config_file=candidate_config/{{ inventory_hostname }}
        diff_file=diff/{{inventory_hostname}}-diff.txt
        commit_changes={{ commit_changes }}

