---
- name: Envio de comandos a equipos playbook-1
  hosts: SW1
  gather_facts: false
  connection: network_cli

  tasks:
  - name: Comando show ip interfaces
    ios_command:
       commands:
         - show vlans
    register: output

  - name: Mostrar el resultado del comando
    debug: var=output

#- name: configurando DNS
#  hosts: cisco_devices
#  connection: network_cli
#  gather_facts: no
#  vars:
#    dns: "1.1.1.1"
#  tasks:
#  - name: configure hostname
#    ios_config:
#       lines: hostname {{ inventory_hostname }}
#       save_when: modified

  - name: configue DNS
    ios_config:
       lines: ip name-server {{dns}}
       save_when: modified
